### ISSUE TITLE
Add option to store foreign_key as string

### ISSUE THREAD

**Issue by d4be4st** [infinum/enumerations#14]
We did some benchmarks and retrieving by string is 200ms slower than integers on a 10 000 000 records big table :) 

insignificant speed improvements over readability and convenience.

**Comment by DamirSvrtan** [comment]
@d4be4st - was the attribute indexed? I wouldn't call that insignificant, 200ms is a lot.

Can you post some benchmarks here?

**Comment by d4be4st** [comment]
Ofc they are. And 200ms is insgnificant when your query is taking 7 seconds :D

count is 11111100 rows:

`EXPLAIN ANALYZE select * from test where symbol_1 = 'symbol_1';`

```
Seq Scan on test  (cost=0.00..220588.41 rows=2207029 width=30) (actual time=0.035..1530.791 rows=2222213 loops=1)
  Filter: ((symbol_1)::text = 'symbol_1'::text)
  Rows Removed by Filter: 8888887
Planning time: 0.047 ms
Execution time: 1643.531 ms
```

`EXPLAIN ANALYZE select * from test where integer_1 = 1;`
```
Seq Scan on test  (cost=0.00..220588.41 rows=2207029 width=30) (actual time=0.052..1409.143 rows=2222213 loops=1)
  Filter: (integer_1 = 1)
  Rows Removed by Filter: 8888887
Planning time: 0.045 ms
Execution time: 1522.627 ms
```

`EXPLAIN ANALYZE select * from test where symbol_2 = 'symbol_1';`
```
Bitmap Heap Scan on test  (cost=58637.03..167924.90 rows=2207029 width=30) (actual time=1840.928..3250.212 rows=2222213 loops=1)
  Recheck Cond: ((symbol_2)::text = 'symbol_1'::text)
  Rows Removed by Index Recheck: 5736828
  Heap Blocks: exact=28959 lossy=52741
  ->  Bitmap Index Scan on test_symbol_2_idx  (cost=0.00..58085.28 rows=2207029 width=0) (actual time=1822.448..1822.448 rows=2222213 loops=1)
        Index Cond: ((symbol_2)::text = 'symbol_1'::text)
Planning time: 0.049 ms
Execution time: 3365.667 ms
```

`EXPLAIN ANALYZE select * from test where integer_2 = 1;`
```
Bitmap Heap Scan on test  (cost=47836.91..157124.77 rows=2207029 width=30) (actual time=626.102..2054.521 rows=2222213 loops=1)
  Recheck Cond: (integer_2 = 1)
  Rows Removed by Index Recheck: 5736828
  Heap Blocks: exact=28959 lossy=52741
  ->  Bitmap Index Scan on test_integer_2_idx  (cost=0.00..53285.15 rows=2207029 width=0) (actual time=618.400..618.400 rows=2222213 loops=1)
        Index Cond: (integer_2 = 1)
Planning time: 0.044 ms
Execution time: 3174.068 ms
```


And from these benchmarks it seems that unindexed versions is faster on a large dataset, and that is interesting.
@DamirSvrtan

**Comment by d4be4st** [comment]
On smaller sets there is no difference

**Comment by DamirSvrtan** [comment]
@d4be4st - you could also do a benchmark with: https://www.postgresql.org/docs/9.1/static/datatype-enum.html

**Comment by d4be4st** [comment]
http://edgeguides.rubyonrails.org/active_record_postgresql.html#enumerated-types

Beside rails not having native support for enums, enums are between strings and integers.

But this has nothing to do with enumerations, because if you want to use enums types instead of strings you only need to change  your database, everyting else would work because enum types act just like strings.

**Comment by d4be4st** [comment]
@petarcurkovic please release a new version and close issue :)

**Comment by petarcurkovic** [comment]
@d4be4st Released :)
