### ISSUE TITLE
Case statement

### ISSUE THREAD

**Issue by DamirSvrtan** [infinum/enumerations#3]
I'm looking at the comment you've erased in your pull request - `# FIXME: for some reason this doesn't work for case..when expressions`.

Please check how to enable using case statements in Ruby using the threequals operator: http://www.skorks.com/2009/08/how-a-ruby-case-statement-works-and-what-you-can-do-with-it/

**Comment by d4be4st** [comment]
Nisam ziher sta je car htio s ovim napraviti :)

**Comment by d4be4st** [comment]
Ok, we figured what car wanted to do with this but is impossible to do:

What @carr wanted (we think):

```
case user.role
when :admin then something
when 2 then something_else
end
```

This is impossible as case works the other way around. This is an proximation of what it does:

```
if :admin == user.role then something
elsif 2 == user.role then something_else
end
```

It calls `===` of the operator in `when` not the one in `case`, so it would call `===` on `Symbol`, then `===` on `Fixnum`
