### ISSUE TITLE
Setting attribute to nil if enumeration value is unknown - surprising?

### ISSUE THREAD

**Issue by neilsmith** [infinum/enumerations#35]
If you set an enumeration value to something unknown, the attribute is set to nil.

I realise this behaviour is (I believe) intentional, as it mentions in the README:
> If you try to set value that is not an Enumeration value, you will actualy set attribute to nil!

However, I found this behaviour surprising, personally - setting the attribute looks like it works, but silently fails.

```ruby
2.4.1 :016 > x.owner = :customer # :customer is, indeed, a valid enumeration value
 => :customer
2.4.1 :017 > x.owner
 => #<Owner:0x007fdb9be2e4c8 @symbol=:customer, @attributes={:name=>"Customer"}>
```
-- all working as expected - but --
```ruby
2.4.1 :018 > x.owner = :sales # this is a typo; this is not a valid enumeration value
 => :sales # But, at first glance, it looks like this has worked
2.4.1 :019 > x.owner
 => nil # However, really, it's just silently set to nil
```

Obviously this is opinion, rather than a bug, but I can imagine people getting caught out by this.

I'd have perhaps expected an exception to be raised if I tried to set an undefined enumeration value. 

(I realise I could have required the presence of "owner", and then the example above would have failed validation should I have later tried to save it; but I imagine there are cases where I may want a nil value for the enumeration - but never a non-existent one.)

I'm happy to look at contributing some code if you agree.

P.S. Many thanks for the great gem; very useful!

**Comment by PetarCurkovic** [comment]
Hi Neil, thanks for your input. 

Initially, we thought that setting `nil` is a good idea because you can use validations to check if enumeration value is set.

Now, we agree that raising an error would be much better than just silently set to `nil`.
We will implement it after PR #37 is merged.

P.S. Glad you like the gem! Thanks!
