### ISSUE TITLE
standard validations

### ISSUE THREAD

**Issue by d4be4st** [infinum/enumerations#39]
I would add standard validations to enumration

When using only in API, a client would get an error here https://github.com/infinum/enumerations/blob/c336d6001f5aa3e170438001e3d36c3c0ad3d96f/lib/enumerations.rb#L90 which does not mean anything to the client.

Would add:

validates #{enumerations}, presence: true, inclusion: #{Enumeraiont}.all

Also would add optional parameter that would disable these validations, same as new belongs_to does

**Comment by lovro-bikic** [comment]
[This is now possible.](https://github.com/infinum/enumerations?tab=readme-ov-file#validating-input)
