### ISSUE TITLE
Add option to add enumerations to virtual attributes

### ISSUE THREAD

**Issue by nikajukic** [infinum/enumerations#44]
It would be useful if you could add enumeration to virtual atribute on AR model defined with attr_accessor. 

E.g.

```
class Cart < ApplicationRecord
  attr_accessor :payment_method
  
  enumeration :payment_method
end
```

Currently it raises `ActiveModel::MissingAttributeError: can’t write unknown attribute 'payment_method'` because I don't have payment_method attribute in carts table.

**Comment by d4be4st** [comment]
@nikajukic have you tried with
`attribute :payment_method, Type::String.new` ?

https://apidock.com/rails/ActiveRecord/Attributes/ClassMethods/attribute

**Comment by d4be4st** [comment]
@nikajukic Did you have any success with the proposed solution? If yes, please close the issue

**Comment by nikajukic** [comment]
@d4be4st yes, attribute + enumeration works fine! Thanks.
