### ISSUE TITLE
When rendering json, default to string value

### ISSUE THREAD

**Issue by melcha** [infinum/enumerations#45]
Currently I'm getting this when rendering JSON:
``` javascript
"role": {
  "symbol": "customer",
  "attributes": {
    "name": "Customer"
  }
}
```

I want this:
``` javascript
"role": "customer"
```

**Comment by d4be4st** [comment]
We wont be able to fix this, unfortunately

All serializers use `send(field_name)` when creating hash before transforming to json. 

you will need to transform the object inside the serializer everytime.
