### ISSUE TITLE
I18n.locale

### ISSUE THREAD

**Issue by gabskoro** [infinum/enumerations#6]
Trenutno to rijesavamo tako da overrideamo name metodu i u njoj vucemo iz lokala, sta mislite, ima li smisla ukomponirati taj feature u sam gem?

Ne znam tko je odgovaran za projekt pa assigneam stefa :)

cc @DamirSvrtan, @janvarljen, @petarcurkovic

**Comment by d4be4st** [comment]
Imas primjer kak ste overridali name?

meni ima smisla, tipa traziti ako postoji t('enumerations.value.name') ili nesto slicno kao sto u activerecordu mozes definirati za translatione za sve attribute fieldove.

**Comment by gabskoro** [comment]
@isBatak ajde zalijepi primjer :)

**Comment by isBatak** [comment]
``

**Comment by isBatak** [comment]
Ovako smo mi to provremeno rijesili.

```
class DepositType < Enumeration::Base
  extend EnumAlphabeticallySortConcern

  values refundable:     { id: 1, name: 'Refundable' },
         non_refundable: { id: 2, name: 'Non-refundable' },
         both:           { id: 3, name: 'Non-refundable + Refundable' },
         advanced:       { id: 4, name: 'Advanced Provisioning Allowance' },
         regattas:       { id: 5, name: 'Deposits for regattas' }

  def name
    I18n.t("deposit_type.#{self.symbol}");
  end
end
```

Moj prijedlog bi bio da se doda simbol :translate kao indentifier da se name vuce iz yml filea...
npr. `values refundable:     { id: 1, name: :translate, description: :translate },`

a yaml file:
```
enumerations:
    deposit_type:
        refundable: 
             name: Refundable
             description: ...
             ...
```

**Comment by janvarljen** [comment]
Imamo već taskove na tu temu na Productiveu:

http://productive-beta.infinum.co/1-infinum/projects/23/tasks

vjerojatno ima smisla da sve to tu prebacimo

**Comment by d4be4st** [comment]
Da bi radilo sa recimo SimpleForm i labelama jer pretpostavljam da uglavnom tamo treba to, samo treba definirati 
`human_attribute_name`
https://github.com/plataformatec/simple_form/blob/e81af052f4bbe9e17e38c668116cd1846c6d275c/lib/simple_form/components/labels.rb#L68
http://apidock.com/rails/v4.2.1/ActiveModel/Translation/human_attribute_name

A u ostatku koda bi mozda onda koristio taj isti `human_attribute_name`, ili definirao vlastiu metodu `localized(attribute)` koja bi u pozadini koristila `human_attribute_name`

**Comment by petarcurkovic** [comment]
Dodana podrška za translatione iz locale fileova.
