### ISSUE TITLE
Moved all back to Base

### ISSUE THREAD

**Issue by d4be4st** [infinum/enumerations#9]
I did a booboo
Pushed my commit to master directly.

https://github.com/infinum/enumerations/commit/4c47e5717e86818be8b01950f5e3bc8a3b5da4f7

I removed Enumeration::Value and moved all that back to Base. Without this we cant define instance_methods directly in enumeration classes as we did before.

Also added #find_by method that tries to do what #find_by does in ActiveRecord.

Any sugestions how we could separate class metods and instance methods in different files maybe? @janvarljen @DamirSvrtan @petarcurkovic

**Comment by petarcurkovic** [comment]
Hi @d4be4st !

I've restored Enumeration::Value class :).
Also, I did some refactoring, improved tests and added bang methods.
Changes are visible in `refactor` branch.
